### ISSUE TITLE
RadarChart category labels

### ISSUE THREAD

**Issue by clisztian** [HanSolo/charts#19]
Greetings Gerrit, 
I was recently trying out your amazing RadarChart, and for some reason I'm not able to reach any place where I can add category values to the radar. Are these coming directly from the YChartItem? If so, I would expect, for example in your RadarChartTest, that 

``YChartItem(RND.nextDouble() * 100, "P" + i); ``

would show P1, P2, etc as categories around the 'radar'. Or am I missing something? 

Anyway, thanks for these amazing javafx libraries!
Cheers

**Comment by HanSolo** [comment]
Yep that‘s correct 👍🏻

**Comment by clisztian** [comment]
Okay, so in running your RadarChartTest example, I'm having a hard time finding the categories. As mentioned, I believe the expected result should show P0...P29 around the radar. Here is the outcome:
Is there something I'm missing?

![image](https://user-images.githubusercontent.com/3885050/88454158-d34cbc00-ce6d-11ea-9ce1-9b6006d8bc24.png)

**Comment by HanSolo** [comment]
Oh now I see, seems I’ve deactivated it. I knew it was in there but I commented it out. If I remember right the reason was that the labels appear outside of the chart and I did not had the time to adjust the chart size correctly. Will take another look at it, sorry for the inconvenience.

**Comment by HanSolo** [comment]
Ok, I've added the possibility to have a list of categories for the YPane (which will be used to visualize the RadarChart). It came with the latest commit (17746095b1d836b0805e6d79ca4396fd6a361208). You can simply pass a list of Category items to the YPane and it will draw them. At the moment the category only has a name and if you have more categories than sectors it will only use the categories up the no of sectors. Please take a look in the RadarChartTest class to see how to use it. 
Just let me know if this works for you or if you miss something so that I can add missing things.
Cheers,
Gerrit
